### ISSUE TITLE
Dragging and dropping images not working

### ISSUE THREAD

**Issue by codemedic** [BoostIO/Boostnote#1026]
Dragging and dropping an image does seem to put the image into the storage folder, but nothing gets added to the markdown.
Is that expected?

I am running 0.8.14 on Linux (KDE) and I am dragging image from Dolphin file manager.

I can provide more debug (or anything else) if you let me know what is required.

**Comment by kazup01** [comment]
Can this feature only when markdown editing mode.
![oct-28-0029 18-15-21](https://user-images.githubusercontent.com/8602615/32133104-2268c13e-bc0c-11e7-9377-a7e92e548832.gif)

But we should improve UX such as can dropping image when markdown preview mode.
We are welcome your pull request. Could you try it?

**Comment by codemedic** [comment]
I was doing this when in "markdown edit mode". It did not work.
Are there any logs or something that I can provide, in order to help you debug this?

**Comment by kazup01** [comment]
Could you try the latest version (v0.8.16)? This problem seems to fixed at v0.8.15. #820

**Comment by codemedic** [comment]
Brilliant! Thanks!
I can confirm that it is fixed in v0.8.16.

**Comment by Zikoel** [comment]
Hi,
Seems that the problem was not solved on all platform! I am from Ubuntu 17.04 and the behavior is that: 
![ezgif-5-4269d8c755](https://user-images.githubusercontent.com/6044789/32700448-e221227c-c7c5-11e7-9069-1ad74aba1043.gif)

My opinion is that when the mouse click on the image boostnote lost the focus and close the drop area.
