### ISSUE TITLE
Update Found notification, but not updating

### ISSUE THREAD

**Issue by Oylex** [BoostIO/Boostnote#1239]
I'm running Boostnote 0.8.17 on Windows 10 with the latest updates (Fall Creators Update)

There is a notification occurring every time I open Boostnote, it says "Update found, preparing to update".

But no matter what I do, nothing happens. I've tried clicking and not clicking on the notification. I've looked in all the menus for an update option, but I can't see anything. I've also tried running it as administrator.

Is it supposed to just be a notification that an update is available? In that case I think you should reword the notification so that it says something like "You can download the new version on our website." instead of "preparing to update".

**Comment by garyhodgson** [comment]
I'm seeing the same behaviour.  

The SquirrelSetup.log (under %USER%\AppData\Local\boost contains multiple lines with: 

  2017-12-05 00:13:20> Program: Starting Squirrel Updater: --checkForUpdate https://github.com/BoostIO/boost-releases/releases/download/v0.8.18

Navigating to that URL in a browser results in a 404

**Comment by garyhodgson** [comment]
For what it's worth, it seems that one can update manually by running:
 
    %USERPROFILE%\AppData\Local\boost\Update.exe  --update https://github.com/BoostIO/boost-releases/releases/download/v0.8.18

and then restarting the app

**Comment by f-unk** [comment]
A collegue and I are having the same problem. In the setup.log the update always gives me the following error:

`2017-12-05 09:42:29> IEnableLogger: Failed to install package to app dir: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Access to the path 'resources' is denied.`

Also, when downloading the windows installer for the new version here:
https://github.com/BoostIO/boost-releases/releases/download/v0.8.18/Boostnote-win.exe

Symantec Endpoint Protection detects this .exe file as a virus and it is deleted automatically preventing us from installing the new version.

Very strange.

**Comment by iursevla** [comment]
Same here.

**Comment by f-unk** [comment]
I ran the updater manually this morning and the update actually seemed to work. The only error in the log was:

`2017-12-07 07:52:02> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: Could not find a part of the path 'C:\Users\kazup\project\Boostnote\resources\app.ico'. ---> System.Net.WebException: Could not find a part of the path 'C:\Users\kazup\project\Boostnote\resources\app.ico'. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\kazup\project\Boostnote\resources\app.ico'.`

Hardcoded path? :)

**Comment by kparkov** [comment]
Also reproducable on Mac here. "Update found" but never applied. Need to download the dmg to update.

**Comment by Rokt33r** [comment]
The problem has been identified. This will be fixed soon.

**Comment by kazup01** [comment]
Hi guys, this bug is fixed yet. Please reload your Boostnote!
Thanks for your waiting!

**Comment by Rokt33r** [comment]
This problem still exists... I'm still investigating.
It seems there are two bugs. The identified one has been fixed but updater still doesn't work.

**Comment by Rokt33r** [comment]
Fixed. https://github.com/BoostIO/Boostnote/pull/1393
You should install v0.8.20 manually because the updater of v0.8.19 is still broken. Sorry for making you inconvenience.

**Comment by pwolter** [comment]
@Rokt33r Looks like the updater is *just* broken as this is still happening on Mac *and* I am on 0.11.8

**Comment by luckydonald** [comment]
@kazup01 
> Please reload your Boostnote!

Doesn't help.
Version 0.11.11 (0.11.11).

![ezgif-1-364e1bb7c438](https://user-images.githubusercontent.com/2737108/50241002-a3eae900-03c6-11e9-9b83-3e4aec312096.gif)

**Comment by luckydonald** [comment]
@Rokt33r  As this seems to be fixed for windows, maybe we should open a new issue for mac?

**Comment by scypher6** [comment]
This is still an issue in 2020! Nothing has been fixed! There are 100's of threads complaining about this! The LEAST that the devs of this app could do is to provide instructions on how to update manually on both Mac and PC. Smh.

**Comment by Flexo013** [comment]
To update manually, simply download the latest installer and it will overwrite/update your current installation.

It does seem that the auto updater isn't properly working (I personally don't use it). 

> There are 100's of threads complaining about this!

I can't find any open issues concerning the auto updater so I will reopen this one.

**Comment by Rokt33r** [comment]
> (I personally don't use it).

Hmm it sounds I definitely should do overhaul auto updater one day soon.

**Comment by arcturus140** [comment]
I don't use it either. (I'm on linux)
Personally, I'm not interested in this feature.  Boostnote is very mature and has all features I'd need. A stable  release would be interesting, maybe with auto updater only for security and bug fixes.

**Comment by Rokt33r** [comment]
@arcturus140 The change wouldn't affect to the linux app because it doesn't support the auto updater.

**Comment by Flexo013** [comment]
Agreeing with @arcturus140 here. I prefer updating my programs manually, so I can see if I like all new features, or if there might be any bugs. On top of that I can do it when it's convenient to me.

All that I would want for "auto" updates is a notification when a new version is out so I can manually go check it, or just dismiss the notification (forever or maybe for a week).

**Comment by scypher6** [comment]
Thanks, I will try to download the newest installer.
