### ISSUE TITLE
Editor/Peview differences in code block colors

### ISSUE THREAD

**Issue by blinker57** [BoostIO/Boostnote#1810]
# Current behavior
Why are there differences in how code blocks look (themes) between the Editor and the Preview? The panda-syntax theme is a prime example — it shows a dark background in the editor and a light background in the preview.

![image](https://user-images.githubusercontent.com/25513852/38779790-49e2fd92-409b-11e8-9ba1-24c0d5570d52.png)
![image](https://user-images.githubusercontent.com/25513852/38779799-67e75324-409b-11e8-87b9-e31d948b77e6.png)
![image](https://user-images.githubusercontent.com/25513852/38779804-859db674-409b-11e8-953e-956fcf74cf8e.png)
Note the differences between the editor and preview.

Thanks — enjoy the product!

# Expected behavior
I expect the theme colors to be the same in every way between the editor code block and the preview code block.

# Steps to reproduce
1. Go to Preferences->Interface and choose panda-syntax for Editor Theme and Preview Code block Theme. Save and return to the MD editor
2. Create a code block and type some code
3. Compare and note the differences in the colors of the code block between the editor and preview
NOTE: I have noticed differences in code block colors between the editor and preview from other themes as well - however, panda-syntax is probably the most blatant since it is the background. It would be nice if all the colors were the same in every way with all themes.

# Environment
- Version : Boostnote 0.11.4
- OS Version and name : Windows 7 SP1 64-bit
Intel i5 - 32GB memory

**Comment by Flexo013** [comment]
This is fixed in the latest version of Boostnote.

**Comment by domclone** [comment]
> This is fixed in the latest version of Boostnote.

still seeing this issue on boostnote version 0.12.1 (0.12.1)
mac os 10.14.6

**Comment by Flexo013** [comment]
@domclone Is this purely the background color that is missing? Or is other styling missing as well?
