### ISSUE TITLE
v0.11.5 image not shown

### ISSUE THREAD

**Issue by eugenia1815** [BoostIO/Boostnote#1980]
# Current behavior
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/33351735/40571818-fb3437de-60e2-11e8-9996-9c224999a69d.png">

# Expected behavior
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/33351735/40571791-9843a52e-60e2-11e8-9f88-90594a2110c0.png">

# Environment

- Version : v0.11.5
- OS Version and name : Sierra 10.12.6

**Comment by Seanybalabala** [comment]
Yes, I have encounted the issue too. Now, images can only be displayed by using absolute path which is quite annoying.

**Comment by i5uhail** [comment]
Able to reproduce the same. Hopefully a fix will be in place soon.

**Comment by hminle** [comment]
I have this issue too, I don't want to upgrade. How to stop upgrade, because v0.11.4 is better, it does not have image issue

**Comment by hminle** [comment]
This is a huge bug, can anyone help?

**Comment by ehhc** [comment]
hi together, i fear it is my fault. I explained the problem here: https://github.com/BoostIO/Boostnote/issues/1941#issuecomment-390644169
I am very sorry for the problems i caused.. i've already submitted a PR that hopefully fixes the problem, but it can't be released before the next version (in 2-3 weeks,,,).

@OnlineVagrant  what is the problem with drag&drop? If there is an error in the development console, could you please post it?

as a current workaround: if you rename the folder "images" at your boostnote storage location to "attachments" it might work again (see the comment linked above for the explanation)

**Comment by OnlineVagrant** [comment]
@ehhc When in edit mode drag and drop works well but in the split view mode it does not display when dragging and dropping. I just realised if you move the cursor by adding another photo or pressing enter the photo gets displayed.

There is an error but I think it is unrelated.

![one](https://user-images.githubusercontent.com/39413259/40581200-a522cd06-6128-11e8-9753-29f3721bfc04.JPG)

![two](https://user-images.githubusercontent.com/39413259/40581203-b09cf9a4-6128-11e8-94cd-85942b2c1bcb.JPG)

![error](https://user-images.githubusercontent.com/39413259/40581204-b7c22ede-6128-11e8-9548-0f7c967098f9.JPG)

**Comment by ehhc** [comment]
@OnlineVagrant thank you for your answer. Yes it is unrelated but it will be (hopefully) fixed with the next release as well :)
Sorry for the problems..

**Comment by eugenia1815** [comment]
Is there a way to downgrade? 

Working with 11.5, when I paste the image I copied, it appears the image with absolute path and the image SHOULD be in the attachment folder. However, it did not create the new image in the 'attachments' folder. All my images gone when I quit Boostnote and open again even I insert the image with the absolute path.

<img width="767" alt="image" src="https://user-images.githubusercontent.com/33351735/40818581-22b350da-659b-11e8-8e44-954680b4c4ed.png">
<img width="611" alt="image" src="https://user-images.githubusercontent.com/33351735/40818594-41dca088-659b-11e8-90a4-eb68cf40a366.png">
My folder is **empty**, without any images

**Comment by ehhc** [comment]
@jonblack actually the root path changed with version 0.11.5.. But with version 0.11.6 a mathod to copy them from the old location to the new one exists..(I'm sorry that i forgot about that in the 0.11.5 version :( ) Obviously it dosen't work though.. :/ 
I just can say we're looking to it... sorry for the problems

**Comment by jonblack** [comment]
I think there are multiple problems. If I manually move the images to the attachments folder it still doesn't load them. The path it's trying to load has the following prefix: `file:///file:///`, which obviously doesn't work.

**Comment by ehhc** [comment]
Hi,
i think/hope both is fixed with https://github.com/BoostIO/Boostnote/pull/2107 
First problem: I have not considered that the old path started with "/:storage" instead of ":storage". -> the double file:// problem..
Second problem: I think the migration doesn’t work because the old way (i'm not completely sure about that) was "/:storage/path/..." with "/". In the first migration try i assumed that it is platform dependent instead of "/" (-> in windows "/:storage\path.." ) But that seems to be a wrong assumption.. i (hope that i) fixed that with the recent PR as well...

Sorry for all the problems again..

**Comment by szjani** [comment]
I still have this problem on Windows 10 with 0.11.13.

As you can see the last backslash `\` is urlencoded to `%5C`, which might be the cause why the image cannot be loaded.

![image](https://user-images.githubusercontent.com/545872/54913993-4bab1200-4ef4-11e9-95d8-f5b28b3ca171.png)
