### ISSUE TITLE
Ctrl+click to follow link not working

### ISSUE THREAD

**Issue by yetAnotherUsernameTaken** [BoostIO/Boostnote#3364]
# Current behavior

Clicking on toc contents does not scroll to linked content in Xubuntu 18.04 .

# Expected behavior

After clicking on toc link, it should scroll to linked or related content.

# Steps to reproduce

1) Make a new note in boostnote.
2) Generate toc 
3) click on toc content

Then you can notice that it does not scroll to linked content.

# Environment

- Version : 0.13
- OS Version and name : xubuntu 18.04

**Comment by Flexo013** [comment]
I can't reproduce this on Ubuntu 16.04.

There were some errors with links not working in version 0.13.0. Those should be fixed in the next release, so hopefully this issue will also be resolved by that.

**Comment by arcturus140** [comment]
this might be caused by a special character. To reproduce we need to know the TOC entry that is failing.

**Comment by yetAnotherUsernameTaken** [comment]
Please check with this markdown note. I am not able to, make the toc links click and make it go to content in xubuntu 18.04.
As you have said, it might issue with recent build, i hope this might be fixed in next version.

[interview questions.txt](https://github.com/BoostIO/Boostnote/files/3858965/interview.questions.txt)
 
Thank you.

**Comment by Flexo013** [comment]
When I create a note with that exact content the TOC links all work fine for me on Ubuntu 16.04. 

Could somebody else with xubuntu 18.04 confirm that this issue exists?

**Comment by ignaciogarcia** [comment]
This happens on MacOS too, it's driving me nuts. Version 0.13.0.

Has been happening for a while now, I must add. I even rolled back to an older version some time ago to recover the functionality, but now I've upgraded to see if the issue had dissapeared and no, it's there.

**Comment by Flexo013** [comment]
@ignaciogarcia Was all TOC links that did not work for you or just scrolling issues?

**Comment by ignaciogarcia** [comment]
I didn't thoroughly click in all TOC links, but the ones I tried didn't work. The "Press Cmd + click to follow link" popup does appear in the editor window, but following the instructions doesn't have any effect. Nor does it if I click on a link in the preview window.

As mentioned, falling back to 0.12.1 fixes the problem IN THE PREVIEW WINDOW. Doesn't work either in the editor window.

I have tried with an old installation (0.11.13) I have at another Mac at home and the behavior is the same; links in the preview window do work, links in the editor window preceded by the popup don't.

**Comment by Flexo013** [comment]
I hope that the link and scroll fixes in the next release (0.14.0) will also fix this, but we'll have to see about that.

**Comment by RichardWPerrott** [comment]
I seems to have stopped working on my Windows 10 Pro. 64-bit too; it was working earlier.

**Comment by Flexo013** [comment]
Can anybody confirm that this is fixed in the 0.14.0-0 [pre-release](https://github.com/BoostIO/boost-releases/releases/tag/v0.14.0-0)?

**Comment by ignaciogarcia** [comment]
Still not working completely in 0.14.0. It does work if you clic on a TOC link in the right pane, but it doesn't if you Cmd-click (as prompted by the popup) in the editor.

**Comment by Flexo013** [comment]
Can confirm that this in-editor Ctrl + click does not work.

**Comment by AWolf81** [comment]
That's still an issue as mentioned in PR #3002.

It is for every link in the editor (see snippet below). Link behavior in the preview is working as expected.

I'll create a PR for this. I think there is code missing in `hyperlink.js` mousedown handler - just normal web links are handled.
I'll try to move the link click handler in a js file so it can be used by preview and editor - so we don't have the code at two locations.

```md
# Tag link test

- Item 1 [#Typescript](:tag:#Typescript)
- Item 2 [#1st tag](:tag:#1st)

# Note link
[XSS plantuml](:note:9a4c36c2-84e9-448a-a01c-eb1e555b7a6b)


# Some dummy text (for line link test)
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

# Line link
[Goto line 3](:line:3)

# External link
[Google](https://www.google.com)
```

**Comment by Flexo013** [comment]
Will be fixed as of 0.15.2
