### ISSUE TITLE
# Can not set a Folder for a new location

### ISSUE THREAD

**Issue by ylhn15** [BoostIO/Boostnote#3372]
# Can not set a Folder for a new location

When I create a new storage location and select a path, the boostnote.json and notes folder is saved in my home directory instead of the selected path.
![screen1](https://user-images.githubusercontent.com/37456409/69260749-ababa280-0bc0-11ea-946b-0b20fbbf48f2.png)
![screen2](https://user-images.githubusercontent.com/37456409/69260750-ac443900-0bc0-11ea-8297-717c249497a5.png)
![screen3](https://user-images.githubusercontent.com/37456409/69260751-ac443900-0bc0-11ea-97be-ea284212e583.png)
![screen4](https://user-images.githubusercontent.com/37456409/69260752-ac443900-0bc0-11ea-8110-121c41b62cd6.png)
Screenshot 2 shows the options screen before selecting a folder, Screenshot 4 after selecting a folder.

# Expected behavior
The boostnote.json file as well as the notes folder should be created and saved in the selected path.

# Steps to reproduce
1. Open Storage Tab in Settings
2. Press "Add Storage Location"
3. Select folder for Location

# Environment
- Version :
  - Boostnote version: 0.13.0
  - Electron: 7.1.1
  - Chrome: 88.0.3904.99
  - Node.js: 12.8.1
- OS Version and name : Linux x64 5.3.11-arch1-1

Many thanks in advance.

**Comment by Flexo013** [comment]
@ylhn15 Could you try clicking the 'OK' button in the top right once you have reached screenshot 3? That should update the location path on the Add Storage page.

**Comment by ylhn15** [comment]
@Flexo013 that's exactly what I did on screenshot 3 resulting in screenshot 4.

**Comment by Flexo013** [comment]
That's very odd. Could you try typing out the path you want manually `/home/yannick/Notes`, just to make sure that part works?

**Comment by ylhn15** [comment]
Typing the path manually worked. 
I only have the example note and example snippet in the default storage.

**Comment by Flexo013** [comment]
Alright, then somehow the location selector is not passing on the correct path on ArchLinux 5.3.11

Thanks for your help with narrowing down the cause!

**Comment by Flexo013** [comment]
@nilsocket In a previous issue you mentioned that you also use ArchLinux. Could you help us by seeing if this issue also occurs on your end?

**Comment by ylhn15** [comment]
@Flexo013 I built the app using your "development" guide by
1. cloning the repo
2. running `yarn`
3. running `yarn run dev`
interestingly, running the app like this the location selector works.

**Comment by olielvewen** [comment]
Hi, 
@Flexo013 
I run the same issue on **Manjaro** an derivate **Archlinux Distribution** and **Cinnamon Environment.**
However, for me, I'm not able to change/add an new directory for my personal Cloud **PCloud.**
I've followed this [https://github.com/BoostIO/Boostnote/wiki/Cloud-Syncing-and-Backup](Tutorial)

```
Kernel: 5.3.12-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.2.0 Desktop: Cinnamon 4.2.4 
           info: cairo-dock wm: muffin dm: LightDM 1.30.0 Distro: Manjaro Linux 
```
I've not the time today for checking your tip writing manual path but soon.

**Comment by Flexo013** [comment]
@ylhn15 Then this issue will most likely be fixed for everybody in the next release (0.14.0). :crossed_fingers:

**Comment by olielvewen** [comment]
@Flexo013 

Thanks for the update and did you have a date for this one ?

**Comment by Flexo013** [comment]
Currently I don't. I'll see if I can figure something out with the releasers.

**Comment by nilsocket** [comment]
@Flexo013 
I'm on `5.3.13-arch1-1`, I have checked it multiple times, I was not able to reproduce the issue.
I was able to add new storage locations without any problem.

@olielvewen , @ylhn15 I think it's better to check once again, by updating your  packages.

If it is reproducible in your case, then there is a chance it is a problem with Desktop Managers, I'm using KDE, It's working fine in my case.

Thank you.

**Comment by Flexo013** [comment]
@nilsocket Thanks so much for checking this on your end and providing such detailed info!

**Comment by olielvewen** [comment]
@nilsocket 
I've checked several times on Cinnamon and I've got the same result => enable to synchronize it.

Following your advice, I've tried on another Desktop manager and another Manjaro distribution.
```Kernel: 5.3.12-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.2.0 
           Desktop: Deepin 15.11 Distro: Manjaro Linux 
```
Like you  can see, I had the last stable kernel and on the both and their last version (of this desktop environment).
Our packages are the last update (hey we are running on Archlinux and Manjaro) ie the stable version 0.13.0. Like You.

Even I'm not using usually KDE, I had a netrunner Debian version on my laptop with it and once time the update of my mint (who is on an external hard drive) will be finished, i've done a go on it.

After, I will try the manual installation for checking if it is working for me too.

Thanks a lot for helping us to resolve this bug

**Comment by ylhn15** [comment]
Thank you for your help, I am currently running GNOME and usually run the package manager once a day looking for upgrades. 

I will try KDE later, as soon as I have time for it.

**Comment by olielvewen** [comment]
@nilsocket 

Sorry for the delay I've been obliged to update several times my laptop. I use it only 2 or 3 times by year. And after, to install pcloud and also and specially boostnote. He wasn't in repository. There was a long time that I've not used debian commands...... 

About boostnote: it is the same version i.e 0.13.0, KDE Plasma 5.14.5. Kernel Linux 5.3.0-2-amd64
Distribution:  netrunner18.03  Debian GNU/Linux bullseye/sid

A folder called notes and a boostnote.json file are created in my dedicated folder on my pcloud storage. Well that 's work but only on KDE . And like I'm not using it often....

To resume: it doesn't work on :+1: 

- Gnome

- Deepin

- Cinnamon

Works on:

- KDE

I think that for the moment is to wait the next version and see what's happen. Anyway, if it is only working on KDE, there are a big bug on this situation.

**Comment by Flexo013** [comment]
Can anybody confirm that this issue is resolved when using the latest [pre-release](https://github.com/BoostIO/boost-releases/releases/tag/v0.14.0-0)?

**Comment by ylhn15** [comment]
Sorry for the late reply, in version 0.14.0 the issue still exists for me.

**Comment by huntantr** [comment]
I'm running 0.14.0 on Windows, and none of the options shown in the first dialog are available.

**Comment by Flexo013** [comment]
@huntantr Could you provide a screenshot of the issue? And are you sure you are running Boostnote and note Boost Note.next?

**Comment by huntantr** [comment]
Here is a screenshot of my preferences options in the windows version. When checking for updates, it says I have the latest.
![image](https://user-images.githubusercontent.com/11739053/72897151-44f55300-3cef-11ea-9928-12cdbfd28ae4.png)

**Comment by amatosg** [comment]
I can confirm on 0.14.0 using Arch Linux.

**Comment by ChrisVim** [comment]
I can confirm on 0.14.0 (Arch Linux), too.

**Comment by Flexo013** [comment]
@huntantr You are using Boost Note.next. [Please go to this repo.](https://github.com/BoostIO/BoostNote.next/issues)

**Comment by wilhelmbecker** [comment]
I can confirm on 0.15.0 (Arch KDE).

Also I cannot export files (as pdf, md ...). Commenting this here, cause it most likely has the same issue cause. Maybe others can confirm this relation?

**Comment by jerome-diver** [comment]
boostnote-0.15.3-1 Archlinux local repo, same unresolved problem.

**Comment by wilhelmbecker** [comment]
Just updated to boostnote 0.16.1-4, which solved the problem for me.
I can now
 - Export notes as pdf
 - Successfully set  a folder for a new storage location

There were recent updates on my Manjaro KDE system (KDE Plasma 5.20.2-1), that forced me to update boostnote. Maybe one of the KDE updates fixed the issue with the location path.

Can anyone else confirm this for the new version?
