### ISSUE TITLE
Nord and Vulcan themes don't work

### ISSUE THREAD

**Issue by incace** [BoostIO/Boostnote#3554]
# Current behavior

Both **Nord** and **Vulcan** are broken on v0.15.3 after update. They both seem to revert to the default theme. I have not checked console logs yet as I don't have the time right now.

# Expected behavior

Themes should show their respective colors.

# Steps to reproduce

Update to v0.15.3 and choose either theme.

# Environment

- Boostnote version: 0.15.3
- OS version and name: macOS 10.13.6

**Comment by maximouche** [comment]
With default theme :
![Screenshot 2020-04-21 at 10 28 36](https://user-images.githubusercontent.com/43822518/79844079-7a2b4300-83bb-11ea-8ae0-8c38b132e8a3.jpg)

**Comment by irimiab** [comment]
It happens only for indented code blocks (those which are under a bullet)

**Comment by Flexo013** [comment]
Confirmed on Windows 10 with 0.15.3.

**Comment by daiyam** [comment]
I've just seen the issue. I will fix it. I won't let my babies be broken... :blush:

**Comment by Flexo013** [comment]
This is solved as of Boostnote Legacy version 0.16.0.

Thanks for your contribution @daiyam ❤️

**Comment by vnmabus** [comment]
The "white text on white background" error is still happening for me in non-dark themes for indented code blocks in version 0.16.1.

**Comment by Flexo013** [comment]
@vnmabus Could you give a screenshot example?

I have tested this on 0.16.1 with both Nord and a non-dark theme in combination with light code blocks. I am unable to reproduce the issue.  
![image](https://user-images.githubusercontent.com/4507015/101978774-cd5a4a80-3c57-11eb-8af8-f19d9ff9f6d8.png)

**Comment by vnmabus** [comment]
Yes of course. This is in 0.16.1 with the default theme:

![imagen](https://user-images.githubusercontent.com/2364173/101999790-d17e7a80-3ce0-11eb-85e6-465120316546.png)

**Comment by Flexo013** [comment]
That's really odd.

This is what I get when using the default interface theme, with default styled code blocks. Could you check that both those settings are set to default? (Make sure that you don't confuse it with editor style.

![image](https://user-images.githubusercontent.com/4507015/102015482-34f9be00-3d5c-11eb-8c31-c52a117e3459.png)

We could try backing up your notes, then uninstalling entirely and reinstalling, because some theme file might be corrupt on your end.

**Comment by daiyam** [comment]
@vnmabus Can you specify the Interface Theme, the Preview's Code Block Theme and Preview's Custom CSS you are using, with a markdown example? I can't reproduce your issue.

**Comment by maximouche** [comment]
It occurs when there is a code block embedded in a bullet/numbered list

<pre>
lalala 
bimbamboom
- bullet1
  hello
  ```
  some very smart code here
  ```
- bullet2
</pre>

Here is the result :
![Screenshot 2020-12-14 at 14 37 35](https://user-images.githubusercontent.com/43822518/102087485-ec083f00-3e19-11eb-9bd5-2d5fb19eea05.jpg)




Here a screenshot a the theme I use
![Screenshot 2020-12-14 at 14 38 06](https://user-images.githubusercontent.com/43822518/102087520-fd514b80-3e19-11eb-9da1-121aaa6d33cf.jpg)

**Comment by vnmabus** [comment]
Yes, at first I though it was only in Windows, but I tried installing the 0.16.1 version in Linux in a different PC (that previously had 0.14 and worked fine) and the same problem occurs.

**Comment by maximouche** [comment]
it's also present on 0.16.1 on OSX

**Comment by daiyam** [comment]
+1

**Comment by daiyam** [comment]
The issue is due to hard coded styles introduced by #3473. Before I move them to [browser/main/lib/dataApi/formatHTML.js](https://github.com/BoostIO/Boostnote/blob/master/browser/main/lib/dataApi/formatHTML.js).
I did remember wondering why it's there...

**Comment by vnmabus** [comment]
> 
> 
> @vnmabus Can you specify the Interface Theme, the Preview's Code Block Theme and Preview's Custom CSS you are using, with a markdown example? I can't reproduce your issue.

The preview code block theme is "dracula" (I never changed it, maybe it was the default in previous versions?).
