### ISSUE TITLE
Editor renders text italic because of underscores in LaTeX code

### ISSUE THREAD

**Issue by huettenhain** [BoostIO/Boostnote#530]
In the editor, Boostnote will sometimes render text as italic because of subscript underscores in LaTeX. My system is Windows 10.

**Ways to reproduce:** Create an MD note and enter: `This function $$F_\ell$$ is not italic.`
**Behaviour:** Everything after the underscore is rendered in italic inside the editor.
**Expected Behaviour:** Everything is rendered in upshape inside the editor.

Note that the bug does **not** occur when you write `This function $$F_k$$ is not italic`, so it is a bit subtle. Note also that the bug only affects the editor, not the display window.

**Comment by huettenhain** [comment]
I realize now this is actually #296 still persisting in some cases.

**Comment by asmsuechan** [comment]
Hi @huettenhain! Thanks for report. I suppose the priority of this issue is low. So I'm not contemplating to deal with soon. If you have a big trouble caused by this issue, let me know. Then I immediately try to solve it! Or, you can send PR :smile:

**Comment by huettenhain** [comment]
Hey @asmsuechan, I completely understand. I completely agree that this is not high priority.

**Comment by kazup01** [comment]
I added to [roadmap](https://github.com/BoostIO/Boostnote/projects/3)!

**Comment by kazup01** [comment]
This is low priority so I’ll close for now. But if more people report this as confusing we can reopen and fix. Thanks!

**Comment by Paalon** [comment]
I hope this is fixed.

**Comment by ptoews** [comment]
This issue still persists, and can also be triggered by `*` in latex code like here:
![image](https://user-images.githubusercontent.com/1062119/52898518-4238d680-31df-11e9-801d-cc91c2329bda.png)
It's irritating because all the following lines are now italics as well and if I don't mention my f* soon again half of the document will be italics.
